# Generated by Django 3.2.7 on 2022-10-12 23:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20221012_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+5538999999999', max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
