[tool.black]
extend-exclude = '''
/(
    | env            
    | \.venv
    | dist
)/
'''

[tool.isort]
default_section = "THIRDPARTY"
force_single_line = true
line_length = 99
skip_glob = ["**/.env*", "**/env/*", "**/.venv/*", "**/docs/*"]